.PHONY: test-small-file
test-small-file:
	cat test/pkg/inputprocessor/fixtures/input-one.txt | go run main.go

.PHONY: test-big-file
test-big-file:
	cat test/pkg/inputprocessor/fixtures/input-two.txt | go run main.go
