global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 1m
    static_configs:
    - targets: ['localhost:9090']

  - job_name: 'node'
    static_configs:
    - targets: ['node-exporter:9100']

  - job_name: 'rest-service'
    static_configs:
    # Notes: use host.docker.internal when running the API server directly on localhost.
    # - targets: ['host.docker.internal:8000']
    - targets: ['app:8000']
